  [[main]]
  name = "HOME"
  identifier = "main"
  weight = 100
  url = "/it/"

  [[main]]
  name = "POST"
  weight = 200
  identifier = "posts"
  url = "/post"
  
  [[main]]
  name = "RISORSE"
  weight = 300
  identifier = "material"
  url = "/risorse"

  [[footer]]
  name = "theme anatole"
  weight = 1
  identifier = "anatole"
  url = "https://github.com/lxndrblz/anatole"