  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/en/"


  [[main]]
  name = "Resources"
  weight = 200
  identifier = "resources"
  url = "/en/resources/"


  [[footer]]
  name = "Anatole theme"
  weight = 1
  identifier = "anatole"
  url = "https://github.com/lxndrblz/anatole"