 main:
  - name: HOME
    weight: 10
    url: '/it'
  - name: POST
    weight: 20
    url: '/post'
  - name: RISORSE
    weight: 30
    url: '/risorse'
footer:
  - name: anatole-theme
    weight: 1
    identifier: anatole
    url: 'https://github.com/lxndrblz/anatole'
