  [[main]]
  name = "HOME"
  identifier = "main"
  weight = 100
  url = "/it/"

  [[main]]
  name = "POST"
  weight = 200
  identifier = "post"
  url = "/post"
  
  [[main]]
  name = "RISORSE"
  weight = 300
  identifier = "risorse"
  url = "/risorse"

  [[main]]
  name = "CONTATTI"
  weight = 300
  identifier = "contacts"
  url = "/contatti"
   
  [[footer]]
  name = "Anatole theme"
  weight = 1
  identifier = "theme"
  url = "https://github.com/lxndrblz/anatole"